### ISSUE TITLE
Stuck in blank line after starting the server + discord invite link is down

### ISSUE THREAD

**Issue by brudermusscode** [f11y11/nfuyu-bot#19]
I have set up everything as stated in the README but when starting the server, it gets stuck at a blank line without an error or anything. The logging had been both set to file and console but nothing happened.

Your Discord Invitiation is expired linked here in your github!

**Comment by f11y11** [comment]
thanks for bringing it to my attention. I've updated the README b3678cd242f9ba7ca179d5eb463df3f269a782ca and made some changes to the logger that'll possibly fix your issue ec4c07214aa4615ca6febf670030a062263a6029.
